/* CONTENIDO PROVISIONAL: edita textos, fechas e imágenes desde este único archivo. */
window.PORTFOLIO_CONTENT = {
  profile: {
    name: 'Jaime Polaina',
    role: 'Arquitecto',
    location: 'Sevilla, España',
    statement: 'Arquitectura serena, precisa y vinculada al lugar. Obra nueva, rehabilitación e interiorismo.',
    about: [
      'Jaime Polaina desarrolla una práctica de arquitectura atenta a la materia, la proporción y la forma en que los espacios se habitan con el tiempo.',
      'El estudio trabaja entre distintas escalas —de la vivienda al espacio colectivo— con especial interés por la rehabilitación, los sistemas constructivos honestos y la relación con el paisaje.',
    ],
    email: 'jaime.pg.arq@gmail.com',
    phone: '+34 662 69 50 66',
    instagram: '@jaimepolaina.arq',
  },
  images: {
    contact: './contact-jaime.png',
    bilbaoCover: './assets/bilbao-01-portada.webp',
    bilbaoDiagram: './bilbao-02-diagrama.png',
    bilbaoPark: './assets/bilbao-02-parque.webp',
    bilbaoPlan01: './assets/bilbao-03-planta.png',
    bilbaoPlan02: './assets/bilbao-04-planta.png',
    bilbaoPlan03: './assets/bilbao-05-planta.png',
    bilbaoSection: './assets/bilbao-06-seccion.png',
    bilbaoCrossSection: './bilbao-07-seccion-transversal.png',
    bilbaoDetail: './assets/bilbao-08-detalle.webp',
    bilbaoPbPe: './assets/bilbao-pb-pe.png',
    cedacerosCover: './assets/cedaceros-01-portada.webp',
    cedacerosCommonAreas: './assets/cedaceros-02-zonas-comunes.webp',
    cedacerosDetail: './assets/cedaceros-03-detalle.png',
    cedacerosGroundPlan: './assets/cedaceros-planta-baja.png',
    cedacerosGroundView01: './assets/cedaceros-planta-baja-vista-01.png',
    cedacerosGroundView02: './assets/cedaceros-planta-baja-vista-02.png',
    cedacerosFirstPlan: './assets/cedaceros-planta-01.png',
    cedacerosLiving2dA: './assets/cedaceros-04-salon-2da.webp',
    cedacerosPlan2dA: './assets/cedaceros-05-planta-2da.png',
    cedacerosLiving2dB: './assets/cedaceros-06-salon-2db.webp',
    cedacerosPlan2dB: './assets/cedaceros-07-planta-2db.png',
    castellanaLivingA: './assets/castellana-01-salon-a.png',
    castellanaBathA: './assets/castellana-02-bano-a.png',
    castellanaLivingCompleteA: './assets/castellana-03-salon-completo-a.png',
    castellanaPreviousA: './assets/castellana-04-estado-previo-a.png',
    castellanaReformedA: './assets/castellana-05-estado-reformado-a.png',
    castellanaFinishesA: './assets/castellana-06-planta-acabados-a.png',
    castellanaDetailsA: './assets/castellana-07-planta-detalles-a.png',
    castellanaLivingB: './assets/castellana-08-salon-b.png',
    castellanaRoomB: './assets/castellana-09-sala-b.png',
    castellanaPreviousB: './assets/castellana-10-estado-previo-b.png',
    castellanaReformedB: './assets/castellana-11-estado-reformado-b.png',
    marbellaCover: './assets/marbella-01-portada.webp',
    marbellaSitePlan: './assets/marbella-02-planta-general.webp',
    marbellaBuilding: './assets/marbella-03-edificio.webp',
    marbellaBim: './assets/marbella-04-bim.jpeg',
    marbellaCommon123: './assets/marbella-04-zonas-comunes-bloques-123.png?v=recorte-20260916',
    marbellaGround123: './assets/marbella-05-planta-baja-bloques-123.png',
    marbellaTypologies: './assets/marbella-06-planta-tipo-tipologias.png',
    marbellaElevationA: './assets/marbella-07-alzado-tipo-a.png',
    marbellaElevationB: './assets/marbella-08-alzado-tipo-b.png',
    marbellaCommon9: './assets/marbella-09-zonas-comunes-edificio-9.png',
    marbellaResidencePlan: './assets/marbella-10-planta-tipo-residencia.png',
    urban: './assets/architecture-urban.png',
    mallorca: './assets/architecture-mallorca.png',
    rural: './assets/architecture-rural.png',
  },
  projects: [
    {
      slug: 'bilbao',
      number: '01',
      title: 'Calle Isasi',
      subtitle: 'Rehabilitación y ampliación residencial',
      location: 'Bilbao, Bizkaia',
      status: 'Proyecto Básico + Proyecto de Ejecución',
      area: '14.141 m²',
      role: 'Desarrollo arquitectónico · BIM',
      verified: true,
      cover: 'bilbaoCover',
      coverLabel: 'VISTA PRINCIPAL',
      gallery: ['bilbaoCover', 'bilbaoPark', 'bilbaoPlan01', 'bilbaoPlan02', 'bilbaoPlan03', 'bilbaoSection', 'bilbaoCrossSection', 'bilbaoDetail', 'bilbaoPbPe'],
      galleryLabels: ['VISTA PRINCIPAL', 'VISTA PARQUE', 'PLANTA 01', 'PLANTA 02', 'PLANTA 03', 'SECCIÓN LONGITUDINAL', 'SECCIÓN TRANSVERSAL', 'DETALLE CONSTRUCTIVO', 'PB+PE'],
      galleryFit: ['cover', 'cover', 'contain', 'contain', 'contain', 'contain', 'contain', 'contain', 'contain'],
      description: 'Rehabilitación y ampliación de una antigua fábrica en la calle Andrés Isasi, Bilbao, para su transformación en un edificio plurifamiliar de 144 viviendas, con locales, garajes y trasteros. El proyecto integra la construcción preexistente en una nueva organización residencial de cinco portales e incorpora dos plantas retranqueadas sobre el volumen existente, resolviendo la relación entre la arquitectura conservada, la ampliación y las nuevas tipologías de vivienda.',
      action: 'Participación dentro del equipo en el desarrollo arquitectónico y BIM del proyecto: modelado en Revit, desarrollo de plantas y tipologías de vivienda, secciones, fachadas, detalles constructivos, normativa y documentación de Proyecto Básico y Proyecto de Ejecución.',
      facts: [
        ['Localización', 'Bilbao, Bizkaia'],
        ['Tipología', 'Rehabilitación y ampliación residencial'],
        ['Fase', 'Proyecto Básico + Proyecto de Ejecución'],
        ['Superficie', '14.141 m²'],
        ['Participación', 'Desarrollo arquitectónico · BIM'],
      ],
    },
    {
      slug: 'marbella',
      number: '02',
      title: 'Senior Living Marbella',
      subtitle: 'Complejo residencial y asistencial',
      location: 'Marbella, Málaga',
      status: 'Proyecto Básico + Proyecto de Ejecución',
      area: '50.000 m²',
      role: 'Desarrollo arquitectónico · BIM',
      verified: true,
      cover: 'marbellaCover',
      coverLabel: 'VISTA GENERAL',
      gallery: ['marbellaCover', 'marbellaSitePlan', 'marbellaBuilding', 'marbellaBim', 'marbellaCommon123', 'marbellaGround123', 'marbellaTypologies', 'marbellaElevationA', 'marbellaElevationB', 'marbellaCommon9', 'marbellaResidencePlan'],
      galleryLabels: ['VISTA GENERAL', 'PLANTA GENERAL', 'EDIFICIO TIPO', 'BIM', 'ZONAS COMUNES · BLOQUES 1, 2 Y 3', 'PLANTA BAJA · BLOQUES 1, 2 Y 3', 'PLANTA TIPO · TIPOLOGÍAS', 'ALZADO TIPO A', 'ALZADO TIPO B', 'ZONAS COMUNES · EDIFICIO 9', 'PLANTA TIPO · EDIFICIO RESIDENCIA'],
      galleryFit: ['cover', 'contain', 'cover', 'contain', 'contain', 'contain', 'contain', 'contain', 'contain', 'contain', 'contain'],
      description: 'Complejo residencial y asistencial de aproximadamente 50.000 m², compuesto por 12 edificios que integran cerca de 300 alojamientos de distintas tipologías. El conjunto combina el programa residencial con espacios comunes vinculados a la salud, la rehabilitación, el deporte y la convivencia, incorporando áreas asistenciales, consultas, gimnasios, piscinas, salas multiusos y otros espacios de servicio.',
      action: 'Participación dentro del equipo en el desarrollo arquitectónico y BIM del proyecto, trabajando en el modelado en Revit, desarrollo de plantas y tipologías de alojamiento, secciones y fachadas, resolución de detalles constructivos, aplicación de normativa y elaboración de documentación para las fases de Proyecto Básico y Proyecto de Ejecución.',
      facts: [
        ['Localización', 'Marbella, Málaga'],
        ['Tipología', 'Complejo residencial y asistencial · Senior Living'],
        ['Fase', 'Proyecto Básico + Proyecto de Ejecución'],
        ['Superficie', '50.000 m²'],
        ['Participación', 'Desarrollo arquitectónico · BIM'],
      ],
    },
    {
      slug: 'cedaceros-9',
      number: '03',
      title: 'Cedaceros, 9',
      subtitle: 'Edificio residencial · 22 viviendas + zonas comunes',
      location: 'Madrid',
      status: 'Proyecto de Ejecución + Interiorismo',
      area: '8.000 m²',
      role: 'Desarrollo arquitectónico · BIM · Interiorismo',
      verified: true,
      cover: 'cedacerosCover',
      coverLabel: 'FACHADA PRINCIPAL',
      gallery: ['cedacerosCover', 'cedacerosGroundPlan', 'cedacerosGroundView01', 'cedacerosGroundView02', 'cedacerosDetail', 'cedacerosFirstPlan', 'cedacerosLiving2dA', 'cedacerosPlan2dA', 'cedacerosLiving2dB', 'cedacerosPlan2dB'],
      galleryLabels: ['FACHADA PRINCIPAL', 'PLANTA BAJA', 'PLANTA BAJA · VISTA 01', 'PLANTA BAJA · VISTA 02', 'DETALLE · BARRA + COPERO', 'PLANTA 01', 'VIVIENDA TIPO 2dA · SALÓN', 'VIVIENDA TIPO 2dA · PLANTA', 'VIVIENDA TIPO 2dB · SALÓN', 'VIVIENDA TIPO 2dB · PLANTA'],
      galleryFit: ['cover', 'contain', 'cover', 'cover', 'contain', 'contain', 'cover', 'contain', 'cover', 'contain'],
      description: 'Cedaceros, 9 es un proyecto residencial de 22 viviendas en Madrid, desarrollado a nivel de proyecto de ejecución e interiorismo. La intervención combina el desarrollo arquitectónico de las viviendas con el diseño detallado de las zonas comunes de planta baja, donde mobiliario fijo, iluminación, materialidad y elementos realizados a medida forman parte de una misma estrategia de proyecto.',
      action: 'Participación en el desarrollo del proyecto de ejecución e interiorismo, incluyendo modelado en Revit/BIM y SketchUp, desarrollo de plantas de viviendas y zonas comunes, detalles constructivos y mobiliario a medida. Desarrollo específico de la barra y el copero de planta baja, documentación de ejecución, contacto con industriales y participación en reuniones de proyecto.',
      facts: [
        ['Localización', 'Madrid'],
        ['Tipología', 'Edificio residencial · 22 viviendas + zonas comunes'],
        ['Fase', 'Proyecto de Ejecución + Interiorismo'],
        ['Superficie', '8.000 m²'],
        ['Participación', 'Desarrollo arquitectónico · BIM · Interiorismo'],
      ],
    },
    {
      slug: 'castellana-a-b',
      number: '04',
      title: 'Castellana A + B',
      subtitle: 'Reforma residencial',
      location: 'Madrid',
      status: 'Proyecto de Ejecución + Interiorismo',
      area: '515 m² + 570 m²',
      role: 'Desarrollo arquitectónico · BIM · Interiorismo',
      verified: true,
      cover: 'castellanaLivingA',
      coverLabel: 'CASTELLANA A · SALÓN',
      gallery: ['castellanaLivingA', 'castellanaBathA', 'castellanaLivingCompleteA', 'castellanaPreviousA', 'castellanaReformedA', 'castellanaFinishesA', 'castellanaDetailsA', 'castellanaLivingB', 'castellanaRoomB', 'castellanaPreviousB', 'castellanaReformedB'],
      galleryLabels: ['CASTELLANA A · SALÓN', 'CASTELLANA A · BAÑO', 'CASTELLANA A · SALÓN COMPLETO', 'CASTELLANA A · ESTADO PREVIO', 'CASTELLANA A · ESTADO REFORMADO', 'CASTELLANA A · PLANTA DE ACABADOS', 'CASTELLANA A · PLANTA Y DETALLES', 'CASTELLANA B · SALÓN COMPLETO', 'CASTELLANA B · SALA', 'CASTELLANA B · ESTADO PREVIO', 'CASTELLANA B · ESTADO REFORMADO'],
      galleryFit: ['cover', 'cover', 'cover', 'contain', 'contain', 'contain', 'contain', 'cover', 'cover', 'contain', 'contain'],
      description: 'Castellana A + B reúne la reforma de dos viviendas de gran superficie en Madrid. El proyecto parte de dos configuraciones existentes diferentes y desarrolla para cada vivienda una organización y un lenguaje interior propios, manteniendo una atención común a la continuidad espacial, la materialidad y el diseño de los elementos integrados. En Castellana A, el proyecto se articula mediante espacios fluidos, geometrías curvas, celosías y revestimientos de madera que construyen una atmósfera cálida y continua. Castellana B adopta un carácter más contenido y ortogonal, donde la madera, las boiseries, las carpinterías y el mobiliario integrado definen las distintas estancias y acompañan la escala longitudinal de la vivienda.',
      action: 'Participé en el desarrollo de la distribución y las plantas de ambas viviendas, así como en el modelado Revit/BIM y la elaboración de documentación de ejecución. Mi trabajo incluyó el desarrollo de detalles constructivos, mobiliario a medida, definición de materiales y acabados, y la realización de renders para la representación del proyecto.',
      facts: [
        ['Localización', 'Madrid'],
        ['Tipología', 'Reforma residencial'],
        ['Superficie', 'Castellana A · 515 m² / Castellana B · 570 m²'],
        ['Participación', 'Desarrollo arquitectónico · BIM · Interiorismo'],
      ],
    },
  ],
  cv: {
    experience: [
      {
        company: 'ESTUDIO INTERIORLAB',
        role: 'Arquitecto',
        period: 'Mayo 2026 – Actualidad',
        location: 'Sevilla',
        paragraphs: [
          'Participación en el desarrollo arquitectónico y de interiorismo de proyectos residenciales, desde la definición del diseño hasta su resolución técnica y constructiva.',
          'Desarrollo de <strong>Proyectos de Ejecución</strong>, elaborando plantas, alzados, secciones, detalles constructivos y documentación técnica mediante <strong>Revit, AutoCAD y SketchUp</strong>.',
          'Diseño y desarrollo de soluciones de interiorismo y <strong>mobiliario a medida</strong>, abordando encuentros constructivos, selección y definición de materiales y resolución técnica de elementos para su correcta ejecución.',
          'Coordinación directa con <strong>industriales, proveedores y talleres</strong> para el desarrollo, viabilidad y definición técnica de soluciones de proyecto.',
          'Participación en reuniones de proyecto y resolución de incidencias y cuestiones técnicas surgidas durante las fases de desarrollo y ejecución.',
        ],
      },
      {
        company: 'BSA CONSULT',
        role: 'Arquitecto Junior',
        period: 'Noviembre 2025 – Mayo 2026',
        location: 'Fuengirola',
        paragraphs: [
          'Participación en el desarrollo arquitectónico y técnico de <strong>proyectos residenciales de gran escala</strong>, trabajando dentro de un entorno colaborativo <strong>BIM/Revit</strong>.',
          'Desarrollo de proyectos complejos de <strong>rehabilitación, ampliación y transformación de edificaciones existentes</strong>, resolviendo la integración entre la preexistencia y las nuevas intervenciones arquitectónicas.',
          'Desarrollo y gestión de <strong>modelos BIM arquitectónicos en Revit</strong>, así como elaboración de documentación correspondiente a las distintas fases de proyecto.',
          'Participación en el desarrollo de <strong>plantas, tipologías residenciales, secciones, fachadas y detalles constructivos</strong>, atendiendo a criterios de diseño, normativa y viabilidad técnica.',
          'Aplicación y comprobación de normativa urbanística y arquitectónica durante el desarrollo de los proyectos.',
        ],
      },
      {
        company: 'VEGA 15 ARQUITECTURA Y URBANISMO',
        role: 'Arquitecto Junior en prácticas',
        period: 'Enero 2025 – Noviembre 2025',
        location: 'Sevilla',
        paragraphs: [
          'Participación en el desarrollo de propuestas arquitectónicas para <strong>proyectos residenciales y terciarios</strong>, colaborando en las distintas fases de diseño y definición técnica.',
          'Desarrollo de proyectos en fases de <strong>Anteproyecto, Proyecto Básico y Proyecto de Ejecución</strong>.',
          'Elaboración de plantas, alzados, secciones, detalles y documentación gráfica y técnica de proyecto.',
          'Apoyo en la resolución constructiva y técnica de los proyectos durante su desarrollo.',
          'Participación en el <strong>seguimiento de obra</strong>, colaborando en la resolución de incidencias y cuestiones técnicas surgidas durante la fase de ejecución.',
        ],
      },
    ],
    education: [
      {
        title: 'Máster International BIM Management according to ISO 19650: Building Information Modelling',
        institution: 'Universidad Pablo de Olavide',
        period: 'Octubre 2025 – Actualidad',
        description: 'Formación especializada en metodología <strong>BIM</strong>, gestión de la información y coordinación de proyectos conforme a los principios y estándares de la <strong>ISO 19650</strong>.',
      },
      {
        title: 'Grado en Fundamentos de Arquitectura',
        institution: 'Universidad de Sevilla',
        period: '2019 – 2025',
      },
    ],
    software: [
      {
        level: 'Nivel profesional',
        tools: 'Revit · AutoCAD · SketchUp · V-Ray · CYPE Estructuras · CYPE MEP · Adobe InDesign',
      },
      {
        level: 'Nivel intermedio',
        tools: 'Archicad · Adobe Photoshop',
      },
    ],
  },
};
