/* CONTENIDO PROVISIONAL: edita textos, fechas e imágenes desde este único archivo. */
window.PORTFOLIO_CONTENT = {
  profile: {
    name: 'Jaime Polaina',
    role: 'Arquitecto',
    location: 'Palma / Madrid',
    statement: 'Arquitectura serena, precisa y vinculada al lugar. Obra nueva, rehabilitación e interiorismo.',
    about: [
      'Jaime Polaina desarrolla una práctica de arquitectura atenta a la materia, la proporción y la forma en que los espacios se habitan con el tiempo.',
      'El estudio trabaja entre distintas escalas —de la vivienda al espacio colectivo— con especial interés por la rehabilitación, los sistemas constructivos honestos y la relación con el paisaje.',
    ],
    email: 'estudio@jaimepolaina.com',
    instagram: '@jaimepolaina.arq',
  },
  images: {
    bilbaoCover: './assets/bilbao-01-portada.webp',
    bilbaoPark: './assets/bilbao-02-parque.webp',
    bilbaoPlan01: './assets/bilbao-03-planta.png',
    bilbaoPlan02: './assets/bilbao-04-planta.png',
    bilbaoPlan03: './assets/bilbao-05-planta.png',
    bilbaoSection: './assets/bilbao-06-seccion.png',
    bilbaoElevation: './assets/bilbao-07-alzado.png',
    bilbaoDetail: './assets/bilbao-08-detalle.webp',
    urban: './assets/architecture-urban.png',
    mallorca: './assets/architecture-mallorca.png',
    rural: './assets/architecture-rural.png',
  },
  projects: [
    {
      slug: 'bilbao',
      number: '01',
      title: 'Bilbao',
      subtitle: 'Rehabilitación y ampliación residencial',
      location: 'Bilbao, Bizkaia',
      status: 'Proyecto Básico + Proyecto de Ejecución',
      area: '14.141 m²',
      role: 'Desarrollo arquitectónico · BIM',
      verified: true,
      cover: 'bilbaoCover',
      coverLabel: 'VISTA PRINCIPAL',
      gallery: ['bilbaoCover', 'bilbaoPark', 'bilbaoPlan01', 'bilbaoPlan02', 'bilbaoPlan03', 'bilbaoSection', 'bilbaoElevation', 'bilbaoDetail'],
      galleryLabels: ['VISTA PRINCIPAL', 'VISTA PARQUE', 'PLANTA 01', 'PLANTA 02', 'PLANTA 03', 'SECCIÓN', 'ALZADO', 'DETALLE CONSTRUCTIVO'],
      galleryFit: ['cover', 'cover', 'contain', 'contain', 'contain', 'contain', 'contain', 'contain'],
      description: 'Rehabilitación y ampliación de una antigua fábrica en la calle Andrés Isasi, Bilbao, para su transformación en un edificio plurifamiliar de 144 viviendas, con locales, garajes y trasteros. El proyecto integra la construcción preexistente en una nueva organización residencial de cinco portales e incorpora dos plantas retranqueadas sobre el volumen existente, resolviendo la relación entre la arquitectura conservada, la ampliación y las nuevas tipologías de vivienda.',
      action: 'Participación dentro del equipo en el desarrollo arquitectónico y BIM del proyecto: modelado en Revit, desarrollo de plantas y tipologías de vivienda, secciones, fachadas, detalles constructivos, normativa y documentación de Proyecto Básico y Proyecto de Ejecución.',
      facts: [
        ['Localización', 'Bilbao, Bizkaia'],
        ['Tipología', 'Rehabilitación y ampliación residencial'],
        ['Fase', 'Proyecto Básico + Proyecto de Ejecución'],
        ['Superficie', '14.141 m²'],
        ['Participación', 'Desarrollo arquitectónico · BIM'],
      ],
    },
    {
      slug: 'marbella',
      number: '02',
      title: 'Marbella',
      subtitle: 'Vivienda y paisaje',
      location: 'Marbella, Málaga',
      status: 'Proyecto',
      area: '380 m²',
      role: 'Diseño y dirección',
      cover: 'mallorca',
      gallery: ['mallorca', 'rural', 'urban'],
      description: 'Casa organizada como una suma de pabellones y espacios intermedios. Los porches, patios y muros de piedra regulan la luz y construyen una relación gradual entre interior, jardín y horizonte.',
      action: 'Concepto arquitectónico, distribución, materialidad, diseño de detalle y coordinación con paisajismo.',
    },
    {
      slug: 'cedaceros-9',
      number: '03',
      title: 'Cedaceros 9',
      subtitle: 'Rehabilitación residencial',
      location: 'Madrid',
      status: 'Construido',
      area: '210 m²',
      role: 'Rehabilitación integral',
      cover: 'urban',
      gallery: ['urban', 'mallorca', 'rural'],
      description: 'Relectura de una vivienda urbana existente a partir de sus proporciones originales. La intervención despeja circulaciones, recupera la luz natural y enlaza las estancias mediante carpinterías y piezas fijas.',
      action: 'Levantamiento, propuesta de rehabilitación, proyecto ejecutivo, selección de materiales y seguimiento de obra.',
    },
    {
      slug: 'trasierra',
      number: '04',
      title: 'Casa de campo en Trasierra',
      subtitle: 'Rehabilitación',
      location: 'Trasierra, Córdoba',
      status: 'En obra',
      area: '460 m²',
      role: 'Arquitecto responsable',
      cover: 'rural',
      gallery: ['rural', 'mallorca', 'urban'],
      description: 'Rehabilitación de una construcción rural entendida como una operación de continuidad. Se conservan la estructura espacial y los muros de piedra, incorporando nuevas capas de madera, cal y vidrio.',
      action: 'Diagnóstico, estrategia de rehabilitación, proyecto arquitectónico, detalle constructivo y dirección de obra.',
    },
    {
      slug: 'san-reus',
      number: '05',
      title: 'Perrera en San Reus',
      subtitle: 'Pequeña arquitectura',
      location: 'Mallorca',
      status: 'Proyecto',
      area: '42 m²',
      role: 'Diseño y desarrollo',
      cover: 'mallorca',
      gallery: ['mallorca', 'urban', 'rural'],
      description: 'Una pieza pequeña y climáticamente eficiente que combina patios, sombras profundas y ventilación cruzada. El proyecto cuida la escala doméstica y el bienestar animal mediante materiales sencillos y duraderos.',
      action: 'Diseño completo, implantación, estudio bioclimático y definición de sistemas constructivos.',
    },
    {
      slug: 'casa-patio',
      number: '06',
      title: 'Casa Patio',
      subtitle: 'Proyecto provisional',
      location: 'Ubicación por definir',
      status: 'Provisional',
      area: '—',
      role: 'Contenido por definir',
      cover: 'rural',
      gallery: ['rural', 'urban', 'mallorca'],
      description: 'Sexto proyecto reservado para completar la selección inicial del portfolio. El texto, las imágenes y los datos se sustituirán cuando se confirme la obra definitiva.',
      action: 'Alcance de la actuación pendiente de definir.',
    },
  ],
  cv: [
    ['2026—', 'Práctica independiente', 'Palma / Madrid'],
    ['2023—25', 'Colaboraciones en arquitectura y rehabilitación', 'España'],
    ['2022', 'Máster habilitante en Arquitectura', 'Centro por completar'],
    ['2021', 'Grado en Fundamentos de la Arquitectura', 'Centro por completar'],
  ],
};
