/* CONTENIDO PROVISIONAL: edita textos, fechas e imágenes desde este único archivo. */
window.PORTFOLIO_CONTENT = {
  profile: {
    name: 'Jaime Polaina',
    role: 'Arquitecto',
    location: 'Palma / Madrid',
    statement: 'Arquitectura serena, precisa y vinculada al lugar. Obra nueva, rehabilitación e interiorismo.',
    about: [
      'Jaime Polaina desarrolla una práctica de arquitectura atenta a la materia, la proporción y la forma en que los espacios se habitan con el tiempo.',
      'El estudio trabaja entre distintas escalas —de la vivienda al espacio colectivo— con especial interés por la rehabilitación, los sistemas constructivos honestos y la relación con el paisaje.',
    ],
    email: 'estudio@jaimepolaina.com',
    instagram: '@jaimepolaina.arq',
  },
  images: {
    urban: './assets/architecture-urban.png',
    mallorca: './assets/architecture-mallorca.png',
    rural: './assets/architecture-rural.png',
  },
  projects: [
    {
      slug: 'bilbao',
      number: '01',
      title: 'Bilbao',
      subtitle: 'Equipamiento urbano',
      year: '2025',
      location: 'Bilbao, Bizkaia',
      status: 'En desarrollo',
      area: '1.240 m²',
      role: 'Arquitecto de proyecto',
      cover: 'urban',
      gallery: ['urban', 'rural', 'mallorca'],
      description: 'Propuesta para un edificio de escala colectiva que articula una esquina urbana mediante una secuencia de umbrales, patios y espacios de encuentro. La materialidad busca continuidad con el carácter mineral de la ciudad.',
      action: 'Desarrollo de concepto, definición volumétrica, coordinación de proyecto y estudio de soluciones de fachada.',
    },
    {
      slug: 'marbella',
      number: '02',
      title: 'Marbella',
      subtitle: 'Vivienda y paisaje',
      year: '2024',
      location: 'Marbella, Málaga',
      status: 'Proyecto',
      area: '380 m²',
      role: 'Diseño y dirección',
      cover: 'mallorca',
      gallery: ['mallorca', 'rural', 'urban'],
      description: 'Casa organizada como una suma de pabellones y espacios intermedios. Los porches, patios y muros de piedra regulan la luz y construyen una relación gradual entre interior, jardín y horizonte.',
      action: 'Concepto arquitectónico, distribución, materialidad, diseño de detalle y coordinación con paisajismo.',
    },
    {
      slug: 'cedaceros-9',
      number: '03',
      title: 'Cedaceros 9',
      subtitle: 'Rehabilitación residencial',
      year: '2023',
      location: 'Madrid',
      status: 'Construido',
      area: '210 m²',
      role: 'Rehabilitación integral',
      cover: 'urban',
      gallery: ['urban', 'mallorca', 'rural'],
      description: 'Relectura de una vivienda urbana existente a partir de sus proporciones originales. La intervención despeja circulaciones, recupera la luz natural y enlaza las estancias mediante carpinterías y piezas fijas.',
      action: 'Levantamiento, propuesta de rehabilitación, proyecto ejecutivo, selección de materiales y seguimiento de obra.',
    },
    {
      slug: 'trasierra',
      number: '04',
      title: 'Casa de campo en Trasierra',
      subtitle: 'Rehabilitación',
      year: '2024',
      location: 'Trasierra, Córdoba',
      status: 'En obra',
      area: '460 m²',
      role: 'Arquitecto responsable',
      cover: 'rural',
      gallery: ['rural', 'mallorca', 'urban'],
      description: 'Rehabilitación de una construcción rural entendida como una operación de continuidad. Se conservan la estructura espacial y los muros de piedra, incorporando nuevas capas de madera, cal y vidrio.',
      action: 'Diagnóstico, estrategia de rehabilitación, proyecto arquitectónico, detalle constructivo y dirección de obra.',
    },
    {
      slug: 'san-reus',
      number: '05',
      title: 'Perrera en San Reus',
      subtitle: 'Pequeña arquitectura',
      year: '2025',
      location: 'Mallorca',
      status: 'Proyecto',
      area: '42 m²',
      role: 'Diseño y desarrollo',
      cover: 'mallorca',
      gallery: ['mallorca', 'urban', 'rural'],
      description: 'Una pieza pequeña y climáticamente eficiente que combina patios, sombras profundas y ventilación cruzada. El proyecto cuida la escala doméstica y el bienestar animal mediante materiales sencillos y duraderos.',
      action: 'Diseño completo, implantación, estudio bioclimático y definición de sistemas constructivos.',
    },
    {
      slug: 'casa-patio',
      number: '06',
      title: 'Casa Patio',
      subtitle: 'Proyecto provisional',
      year: '2026',
      location: 'Ubicación por definir',
      status: 'Provisional',
      area: '—',
      role: 'Contenido por definir',
      cover: 'rural',
      gallery: ['rural', 'urban', 'mallorca'],
      description: 'Sexto proyecto reservado para completar la selección inicial del portfolio. El texto, las imágenes y los datos se sustituirán cuando se confirme la obra definitiva.',
      action: 'Alcance de la actuación pendiente de definir.',
    },
  ],
  cv: [
    ['2026—', 'Práctica independiente', 'Palma / Madrid'],
    ['2023—25', 'Colaboraciones en arquitectura y rehabilitación', 'España'],
    ['2022', 'Máster habilitante en Arquitectura', 'Centro por completar'],
    ['2021', 'Grado en Fundamentos de la Arquitectura', 'Centro por completar'],
  ],
};
